### ISSUE TITLE
Loop Scroll Content

### ISSUE THREAD

**Issue by CJHersh** [mickaelchanrion/rolly#1]
First of all, thank you for sharing this lib and for putting together incredibly detailed documentation. 

I'm trying to create a scrolling loop with your lib and wanted to see if you had any suggestions. I'm focused on updating the globalState based on scroll value but haven't got it working yet. Any ideas would be greatly appreciated - and feel free to close this issue if it's too off-topic. 

Thanks!

**Comment by mickaelchanrion** [comment]
Hey man!
Why did you close the issue? You solved it?

As per my understanding, when you reach the end of your scrolling content, you want to go back to position 0. Right?

Thanks for your feedback, I appreciate that :)
There's still some improvements and fixes to do on the lib tho. Like the scrollTo method is not working anymore cuz I recently made huge changes on the lib and I forgot to update this one.
