### ISSUE TITLE
Window Event Listener not working

### ISSUE THREAD

**Issue by rodolfosarno** [mickaelchanrion/rolly#10]
Hello,

I love Rolly and really want to make the most of it, however I'm having an issue when I try to disable all hover states  when scrolling the page.

If "**native:false**" the **Prevent Hover** script below doesn't work. If "**native:true**" the script works but the smooth scroll gets very laggy and doesn't work on mobile devices anymore.

Could anyone give me a hand?

Thank you

`//Prevent Hover

var body = document.body, timer;

window.document.addEventListener('scroll', function() {
  clearTimeout(timer);
  if(!body.classList.contains('disable-hover')) {
    body.classList.add('disable-hover')
  }
   
  timer = setTimeout(function(){
    body.classList.remove('disable-hover')
  },500);
      
}, false);

//Rolly.js

const view = document.querySelector('.smooth_scroll');
  const r = rolly({
    view,
    native: false,
    preload: true,  
  });

r.init();`

**Comment by mickaelchanrion** [comment]
Hello @rodolfosarno,
Rolly changes the whole behavior of scrolling so whenever you want to do something about it, I would recommend to always use Rolly's API in favour of the native one.

As per my understanding, you want to:
- add a class to the body when scrolling starts
- remove that class when scrolling stops

Check out the api reference:
https://mickaelchanrion.github.io/rolly/api/#changestart
https://mickaelchanrion.github.io/rolly/api/#changeend

You could have something like that:
```
const r = rolly ({
  view,
  changeStart() {
    body.classList.add('disable-hover')
  },
  changeEnd() {
    body.classList.remove('disable-hover')
  }
})
```

**Comment by rodolfosarno** [comment]
Hey @mickaelchanrion,

Thanks very much for getting back to me and I appreciate your help. My JS knowledge is not the best as I am not a developer. 

I've just tried your script and a few other ways of doing it but unfortunately it still doesn't work.

It seems like Rolly isn't able to ready the body tag even within the changeStart method. Any thoughts?

**Comment by mickaelchanrion** [comment]
In my example, i'm using `body` which is the variable that you created above. Please make sure that this variable exists. Or even simpler: you can directly get the body  from the global variable `document` and manipulate it
```
document.body.classList.add('disable-hover')
document.body.classList.remove('disable-hover')
```

**Comment by rodolfosarno** [comment]
Yep I added the `variable` and also tried using `document.body.classList.add('disable-hover')`
`document.body.classList.remove('disable-hover')` but had no success unfortunately. But that’s ok. I’ll keep trying other options and see if I can come up with a solution. Thanks heaps for your help anyway. Cheers

**Comment by rodolfosarno** [comment]
@mickaelchanrion I've found the issue. Apparently I wasn't using the most up to date library. All good now :) Thanks again.
