### ISSUE TITLE
Question: how update scene for barba.js

### ISSUE THREAD

**Issue by dkrnl** [mickaelchanrion/rolly#28]
Hi!

Thx for awesome library!

We using [barba.js](https://barba.js.org/docs/getstarted/intro/) for transitions between website pages.

How reset (destroy and create new) scenes without destroy rolly instance?

**Comment by mickaelchanrion** [comment]
Hey! 
You could try to use [the method `reload()`](https://mickaelchanrion.github.io/rolly/api/#reload). This will destroy all scenes, then look for any scene present in the DOM and init them.

You could still destroy the rolly instance (i.e.: in the hook `beforeLeave` of your view Barba) and create a new one after the transition of your page.

Sorry for the delayed answer.
